services:
  localstack:
    image: localstack/localstack
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    hostname: localstack
    environment:
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=localstack
    env_file:
      - .env
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "./localstack-setup.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - food-order-network

  food_order_pagamento:
    container_name: food_order_pagamento
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - food-order-network

networks:
  food-order-network:
    name: food-order-network
    driver: bridge
