name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.0'
          otp-version: '26.0'
      - name: Install dependencies
        run: mix deps.get
      - name: Compile project
        run: mix compile
      - name: Build release
        run: mix release
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: diegogl12/food-order-pagamento:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: main-repo
      
      - name: Checkout Terraform repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/food-order-terraform
          path: food-order-terraform
          token: ${{ secrets.GH_PAT }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Init
        working-directory: food-order-terraform
        run: terraform init
      
      - name: Terraform Apply
        working-directory: food-order-terraform
        run: terraform apply -auto-approve
        
      - name: Update kubeconfig
        working-directory: food-order-terraform
        run: |
          aws eks update-kubeconfig --region us-east-1 --name $(terraform output -raw cluster_name)
      
      - name: Deploy to Kubernetes
        working-directory: food-order-terraform
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout restart deployment app-db-deployment
